# Generated by Django 2.1.1 on 2018-09-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nav',
            options={'ordering': ['-create_time'], 'verbose_name': '导航条', 'verbose_name_plural': '导航条'},
        ),
    ]
