# Generated by Django 2.1.1 on 2018-09-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zcomments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
